package exceptions;

import java.io.IOException;

public class Demo2 {
	 public  void test2() throws IOException
	 {
		 
		 //Demo2 ref2 = new Demo2();
		 
		 System.out.println("Inside test2 method");
		  throw new IOException();
		 
	 }

}
